import { Bell, Check, Loader2, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function NotificationInbox({ open, onClose }: { open: boolean; onClose: () => void }) {
  const notifications = trpc.fleet.notifications.useQuery(undefined, { enabled: open });
  const preferences = trpc.fleet.notificationPreferences.useQuery(undefined, { enabled: open });
  const updatePreferences = trpc.fleet.updateNotificationPreferences.useMutation({ onSuccess: () => { preferences.refetch(); toast.success("Notification preferences saved"); }, onError: (error) => toast.error("Preferences could not be saved", { description: error.message }) });
  const markRead = trpc.fleet.markNotificationsRead.useMutation({ onSuccess: () => notifications.refetch() });
  if (!open) return null;
  const prefs = preferences.data || { roleChanges: true, adminActions: true, toastEnabled: true };
  const toggle = (key: "roleChanges" | "adminActions" | "toastEnabled") => updatePreferences.mutate({ ...prefs, [key]: !prefs[key] });
  return <div className="drawer-backdrop" onClick={onClose}><aside className="notification-inbox" onClick={(event) => event.stopPropagation()}><div className="notification-inbox-head"><div><p className="eyebrow">OPERATOR INBOX</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-ink">Notifications</h2><p className="mt-1 text-sm text-slate-500">Role and department updates delivered to your account.</p></div><button className="icon-button" onClick={onClose} aria-label="Close notifications"><X size={18} /></button></div><div className="notification-preferences"><div><p className="eyebrow">PREFERENCES</p><p className="mt-1 text-xs text-slate-500">Choose which updates appear in your inbox and as toasts.</p></div><label><input type="checkbox" checked={prefs.roleChanges} onChange={() => toggle("roleChanges")} /> Role changes</label><label><input type="checkbox" checked={prefs.adminActions} onChange={() => toggle("adminActions")} /> Admin actions</label><label><input type="checkbox" checked={prefs.toastEnabled} onChange={() => toggle("toastEnabled")} /> Toast alerts</label></div><div className="notification-inbox-actions"><span className="text-xs text-slate-400">{notifications.data?.length || 0} recent notifications</span><button className="quiet-button compact" onClick={() => markRead.mutate()} disabled={markRead.isPending}>{markRead.isPending ? <Loader2 size={14} className="spin" /> : <Check size={14} />} Mark all read</button></div><div className="notification-list">{notifications.isLoading && <div className="empty-state"><Loader2 size={20} className="spin" /><p>Loading inbox…</p></div>}{!notifications.isLoading && !notifications.data?.length && <div className="empty-state"><Bell size={20} /><p>Your inbox is clear.</p></div>}{notifications.data?.map((item) => <article className={`notification-item ${item.readAt ? "read" : "unread"}`} key={item.id}><div className="notification-item-mark"><Bell size={14} /></div><div className="min-w-0"><div className="flex items-start justify-between gap-3"><strong className="text-sm text-ink">{item.title}</strong>{!item.readAt && <span className="notification-unread">NEW</span>}</div><p className="mt-1 text-sm leading-5 text-slate-500">{item.message}</p><time className="mt-2 block text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</time></div></article>)}</div></aside></div>;
}
